import { LevelConfig } from './types';

export const LEVELS: LevelConfig[] = [
  {
    id: 'basic-crossing',
    name: 'Classic Crossing',
    description: 'Vier Zufahrten, zwei Signalphasen, keine Abbiegespuren.',
    geometry: {
      board: 900,
      roadHalf: 86,
      laneOffset: 43,
      start: -58,
      carLength: 58,
      carWidth: 32,
      stopLineOffset: 18,
    },
    timings: {
      gameMs: 90_000,
      updateMs: 1000 / 30,
      yellowMs: 1800,
      redYellowMs: 480,
      allRedMs: 900,
      brakeLightHoldMs: 260,
      brakeLightStopHoldMs: 420,
    },
    traffic: {
      lives: 5,
      maxVehicles: 34,
      maxQueuePerApproach: 12,
      spawnInitialMs: 1500,
      spawnBaseMs: 2450,
      spawnVarianceMs: 760,
      spawnPressureBoostMaxMs: 260,
      spawnPressureScoreFactor: 0.12,
      safeGap: 70,
      stopEpsilon: 0.5,
      sportChance: 0.045,
      motorcycleChance: 0.05,
      maxMotorcyclesPerApproach: 1,
    },
    scoring: {
      pointsPerCar: 10,
      minPointsPerCar: 2,
      targetWaitMs: 8000,
      streakBonusEvery: 5,
      streakBonusStep: 2,
      streakBonusMax: 20,
    },
    approaches: [
      { direction: 'north', label: 'Nord', phaseId: 'northSouth', lanes: [{ id: 'main', turns: ['straight'] }] },
      { direction: 'south', label: 'Sud', phaseId: 'northSouth', lanes: [{ id: 'main', turns: ['straight'] }] },
      { direction: 'east', label: 'Ost', phaseId: 'eastWest', lanes: [{ id: 'main', turns: ['straight'] }] },
      { direction: 'west', label: 'West', phaseId: 'eastWest', lanes: [{ id: 'main', turns: ['straight'] }] },
    ],
    phases: [
      { id: 'northSouth', label: 'Nord/Sud', directions: ['north', 'south'], controlKey: 'ArrowUp' },
      { id: 'eastWest', label: 'Ost/West', directions: ['east', 'west'], controlKey: 'ArrowLeft' },
    ],
    controlButtons: [
      {
        id: 'north-south-green',
        label: 'Nord / Sud',
        color: 'green',
        mode: 'latched',
        action: { type: 'phase', phaseId: 'northSouth' },
        controlKey: 'ArrowUp',
      },
      {
        id: 'east-west-green',
        label: 'Ost / West',
        color: 'green',
        mode: 'latched',
        action: { type: 'phase', phaseId: 'eastWest' },
        controlKey: 'ArrowLeft',
      },
      {
        id: 'north-south-all-green',
        label: 'Nord / Sud Komplett',
        color: 'blue',
        mode: 'latched',
        action: { type: 'scene', phaseIds: ['northSouthThrough', 'northSouthLeft'] },
      },
      {
        id: 'all-open-green',
        label: 'Alle Gruppen',
        color: 'amber',
        mode: 'latched',
        action: { type: 'scene', phaseIds: ['northSouthThrough', 'northSouthLeft', 'eastWest'] },
      },
      {
        id: 'all-red-stop',
        label: 'Alle rot',
        color: 'red',
        mode: 'momentary',
        action: { type: 'allRed' },
      },
    ],
  },
  {
    id: 'dual-lane-left-turn',
    name: 'NS Linksabbieger',
    description: 'Oben und unten je eine separate Linksabbiegerspur mit eigener Signalgruppe.',
    geometry: {
      board: 1120,
      roadHalf: 120,
      laneOffset: 60,
      start: -140,
      carLength: 56,
      carWidth: 30,
      stopLineOffset: 18,
    },
    timings: {
      gameMs: 90_000,
      updateMs: 1000 / 30,
      yellowMs: 1800,
      redYellowMs: 480,
      allRedMs: 900,
      brakeLightHoldMs: 260,
      brakeLightStopHoldMs: 420,
    },
    traffic: {
      lives: 5,
      maxVehicles: 46,
      maxQueuePerApproach: 14,
      spawnInitialMs: 1350,
      spawnBaseMs: 2250,
      spawnVarianceMs: 680,
      spawnPressureBoostMaxMs: 260,
      spawnPressureScoreFactor: 0.12,
      safeGap: 70,
      stopEpsilon: 0.5,
      sportChance: 0.045,
      motorcycleChance: 0.05,
      maxMotorcyclesPerApproach: 1,
    },
    scoring: {
      pointsPerCar: 10,
      minPointsPerCar: 2,
      targetWaitMs: 8000,
      streakBonusEvery: 5,
      streakBonusStep: 2,
      streakBonusMax: 20,
    },
    approaches: [
      {
        direction: 'north',
        label: 'Nord',
        phaseId: 'northThrough',
        lanes: [
          { id: 'through', turns: ['straight'], offset: 80, phaseId: 'northThrough' },
          { id: 'left', turns: ['left'], offset: 0, phaseId: 'northLeft' },
        ],
      },
      {
        direction: 'south',
        label: 'Sud',
        phaseId: 'southThrough',
        lanes: [
          { id: 'through', turns: ['straight'], offset: 80, phaseId: 'southThrough' },
          { id: 'left', turns: ['left'], offset: 0, phaseId: 'southLeft' },
        ],
      },
      {
        direction: 'east',
        label: 'Ost',
        phaseId: 'eastWest',
        lanes: [{ id: 'through', turns: ['straight'], offset: 60, phaseId: 'eastWest' }],
      },
      {
        direction: 'west',
        label: 'West',
        phaseId: 'eastWest',
        lanes: [{ id: 'through', turns: ['straight'], offset: 60, phaseId: 'eastWest' }],
      },
    ],
    phases: [
      { id: 'northThrough', label: 'Nord Gerade', directions: ['north'], controlKey: 'ArrowUp' },
      { id: 'northLeft', label: 'Nord Links', directions: ['north'], controlKey: 'ArrowRight' },
      { id: 'southThrough', label: 'Sud Gerade', directions: ['south'] },
      { id: 'southLeft', label: 'Sud Links', directions: ['south'] },
      { id: 'eastWest', label: 'Ost/West', directions: ['east', 'west'], controlKey: 'ArrowLeft' },
    ],
    controlButtons: [
      {
        id: 'north-south-straight',
        label: 'N/S Gerade',
        color: 'green',
        mode: 'latched',
        action: { type: 'scene', phaseIds: ['northThrough', 'southThrough'] },
        controlKey: 'ArrowUp',
      },
      {
        id: 'north-south-left',
        label: 'N/S Links',
        color: 'amber',
        mode: 'latched',
        action: { type: 'scene', phaseIds: ['northLeft', 'southLeft'] },
        controlKey: 'ArrowRight',
      },
      {
        id: 'east-west-green',
        label: 'Ost / West',
        color: 'green',
        mode: 'latched',
        action: { type: 'phase', phaseId: 'eastWest' },
        controlKey: 'ArrowLeft',
      },
      {
        id: 'north-complete',
        label: 'Nord Komplett',
        color: 'blue',
        mode: 'latched',
        action: { type: 'scene', phaseIds: ['northThrough', 'northLeft'] },
      },
      {
        id: 'south-complete',
        label: 'Sud Komplett',
        color: 'blue',
        mode: 'latched',
        action: { type: 'scene', phaseIds: ['southThrough', 'southLeft'] },
      },
      {
        id: 'all-red-stop',
        label: 'Alle rot',
        color: 'red',
        mode: 'momentary',
        action: { type: 'allRed' },
      },
    ],
  },
];

export const DEFAULT_LEVEL_ID = LEVELS[0].id;

export function getLevelById(levelId: string) {
  return LEVELS.find((level) => level.id === levelId) || LEVELS[0];
}
